version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: taller_postgres
    environment:
      POSTGRES_DB: taller_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: taller_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taller.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    # IMPORTANTE: Reemplaza TU_USUARIO_GITHUB por tu usuario
    image: ghcr.io/alexisj3489/taller-devops-flask:1.0.0
    container_name: taller_flask
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data: